import './globals.css';
import type { Metadata } from 'next';
import { fredoka } from './ui/fonts';
import TimeoutModal from './ui/components/timeout/TimeoutModal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={fredoka.className}>
        <main className='mobile:min-w-screen-mobile relative desktop:min-w-screen-desktop tablet:min-w-screen-tablet flex h-full min-h-screen flex-col items-center justify-between'>
          {children}
          <TimeoutModal />
        </main>
      </body>
    </html>
  );
}
