import './globals.css';
import type { Metadata } from 'next';

import Image from 'next/image';
import BlobSVG from './ui/svgs/BlobSVG';
import { fredoka } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={fredoka.className}>
        <main className='mobile:min-w-screen-mobile desktop:min-w-screen-desktop tablet:min-w-screen-tablet flex h-full min-h-screen flex-col items-center justify-between'>
          <div className='relative flex flex-col place-content-end items-center mobile:h-[770.68px] mobile:w-[834.11px] tablet:h-[1173px] tablet:w-[1195.54px] desktop:h-[1036.68px] desktop:w-[1122px]'>
            <Image
              fill
              objectFit='contain'
              className='bg-clip-content'
              alt='sharon'
              src={'/SharonVector.png'}
            />

            <BlobSVG width={1122} height={1036.68} />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
